# Generated by Django 4.0.4 on 2022-05-22 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'user_books_favorites',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='linked_by',
            field=models.ManyToManyField(through='core.BookUsers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(db_column='user_id', max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='fio'),
        ),
        migrations.AddField(
            model_name='bookusers',
            name='book',
            field=models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='core.book', verbose_name='fio'),
        ),
        migrations.AddField(
            model_name='bookusers',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
